#Evelyn ResourcePack by JoseMarcellio
#evelyn.bypass for bypass resourcepack!
#use /n on kick for next line!

EvelynResourcePack:
  Delay: 1 #second
  URL-Link: "your-resourcepack-url"

  Title:
    Accept:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eAccept Downloading ResourcePack!"
      FadeIn: 5
      Stay: 5
      FadeOut: 5
      Enable: true

    Success:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eSuccess Downloading ResourcePack!"
      FadeIn: 5
      Stay: 5
      FadeOut: 5
      Enable: true

  Messages:
    Success:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eSuccess Downloading ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true

    Accept:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eAccept Downloading ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true

  Kick:
    Declined:
      Messages: "&6&lEvelynResourcePack\n&ePlease accept resourcepack!\n &eor enable resourcepack!"
      Enable: true
    Failed:
      Messages: "&6&lEvelynResourcePack\n&eFailed download resourcepack!"
      Enable: true