#Evelyn ResourcePack by JoseMarcellio
#evelyn.bypass for bypass resourcepack!
#use /n on kick for next line!

EvelynResourcePack:
  Delay: 1 #second
  URL-Link: "your-resourcepack-url"

  Messages:
    Enable: true
    Success:
      - "&b&m                                                          &b"
      - ""
      - "              &6&lEvelynResourcePack"
      - "     &eSuccess Downloading ResourcePack!"
      - ""
      - "&b&m                                                          &b"
    Accept:
      - "&b&m                                                          &b"
      - ""
      - "              &6&lEvelynResourcePack"
      - "     &eAccept Downloading ResourcePack!"
      - ""
      - "&b&m                                                          &b"

  Kick:
    Enable: true
    Declined: "&6&lEvelynResourcePack\n&ePlease accept resourcepack!\n &eor enable resourcepack!"
    Failed: "&6&lEvelynResourcePack\n&eFailed download resourcepack!"

