#Evelyn ResourcePack by JoseMarcellio
#evelyn.bypass for bypass resourcepack!
#use /n on kick for next line!

EvelynResourcePack:
  Delay: 1 #second
  URL-Link: "your-resourcepack-url"

  ActionBar:
    Accept:
      Messages: "&eAccept Downloading ResourcePack!"
      Duration: 2 #second
      Enable: true
    Success:
      Messages: "&eSuccess Downloading ResourcePack!"
      Duration: 2 #second
      Enable: true
    Failed:
      Messages: "&eFailed Downloading ResourcePack!"
      Duration: 2 #second
      Enable: true
    Declined:
      Messages: "&eYou Declined ResourcePack!"
      Duration: 2 #second
      Enable: true

  Sound:
    Accept:
      Sound: "LEVEL_UP"
      Volume: 1
      Pitch: 1
      Enable: true
    Success:
      Sound: "LAVA_POP"
      Volume: 1
      Pitch: 1
      Enable: true
    Failed:
      Sound: "VILLAGER_NO"
      Volume: 1
      Pitch: 1
      Enable: true
    Declined:
      Sound: "ANVIL_BREAK"
      Volume: 1
      Pitch: 1
      Enable: true

  Title:
    Accept:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eAccept Downloading ResourcePack!"
      FadeIn: 5 #tick
      Stay: 40 #tick
      FadeOut: 5 #tick
      Enable: true
    Success:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eSuccess Downloading ResourcePack!"
      FadeIn: 5 #tick
      Stay: 40 #tick
      FadeOut: 5 #tick
      Enable: true
    Failed:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eFailed Downloading ResourcePack!"
      FadeIn: 5 #tick
      Stay: 40 #tick
      FadeOut: 5 #tick
      Enable: true
    Declined:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eYou Declined ResourcePack!"
      FadeIn: 5 #tick
      Stay: 40 #tick
      FadeOut: 5 #tick
      Enable: true

  Messages:
    Success:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eSuccess Downloading ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true
    Accept:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eAccept Downloading ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true
    Declined:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eYou Declined ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true
    Failed:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eFailed Downloading ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true

  Kick:
    Declined:
      Messages: "&6&lEvelynResourcePack\n&ePlease accept resourcepack!\n &eor enable resourcepack!"
      Enable: true
    Failed:
      Messages: "&6&lEvelynResourcePack\n&eFailed download resourcepack!"
      Enable: true