#Evelyn ResourcePack by JoseMarcellio
#evelyn.bypass for bypass resourcepack!
#use /n on kick for next line!
#use %player% to get player name on discord-webhook
#if you want tO use discord web-hook
#read this https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
#set URL-Link with your discord webhook link
#and set Enable: true

EvelynResourcePack:
  Delay: 1 #second
  URL-Link: "your-resourcepack-url"

  Lock:
    Join:
      Enable: true

  Unlock:
    Accept:
      Enable: false
    Success:
      Enable: true
    Failed:
      Enable: false
    Declined:
      Enable: false

  Discord-Webhook:
    URL-Link: "your-discord-webhook-url"
    Bypass:
      Author: "Evelyn Webhook"
      Profile: "https://minotar.net/helm/%player%/100.png"
      Title: "EvelynResourcePack"
      Description: "%player% Bypass Downloading ResourcePack!"
      Enable: false
    Accept:
      Author: "Evelyn Webhook"
      Profile: "https://minotar.net/helm/%player%/100.png"
      Title: "EvelynResourcePack"
      Description: "%player% Accept Downloading ResourcePack!"
      Enable: false
    Success:
      Author: "Evelyn Webhook"
      Profile: "https://minotar.net/helm/%player%/100.png"
      Title: "EvelynResourcePack"
      Description: "%player% Success Downloading ResourcePack!"
      Enable: false
    Failed:
      Author: "Evelyn Webhook"
      Profile: "https://minotar.net/helm/%player%/100.png"
      Title: "EvelynResourcePack"
      Description: "%player% Failed Downloading ResourcePack!"
      Enable: false
    Declined:
      Author: "Evelyn Webhook"
      Profile: "https://minotar.net/helm/%player%/100.png"
      Title: "EvelynResourcePack"
      Description: "%player% Declined ResourcePack!"
      Enable: false

  ActionBar:
    Bypass:
      Messages: "&eBypass Downloading ResourcePack!"
      Duration: 2 #second
      Enable: true
    Accept:
      Messages: "&eAccept Downloading ResourcePack!"
      Duration: 2 #second
      Enable: true
    Success:
      Messages: "&eSuccess Downloading ResourcePack!"
      Duration: 2 #second
      Enable: true
    Failed:
      Messages: "&eFailed Downloading ResourcePack!"
      Duration: 2 #second
      Enable: true
    Declined:
      Messages: "&eYou Declined ResourcePack!"
      Duration: 2 #second
      Enable: true

  Sound:
    Bypass:
      Sound: "LEVEL_UP"
      Volume: 1
      Pitch: 1
      Enable: true
    Accept:
      Sound: "LEVEL_UP"
      Volume: 1
      Pitch: 1
      Enable: true
    Success:
      Sound: "LAVA_POP"
      Volume: 1
      Pitch: 1
      Enable: true
    Failed:
      Sound: "VILLAGER_NO"
      Volume: 1
      Pitch: 1
      Enable: true
    Declined:
      Sound: "ANVIL_BREAK"
      Volume: 1
      Pitch: 1
      Enable: true

  Title:
    Bypass:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eBypass Downloading ResourcePack!"
      FadeIn: 5 #tick
      Stay: 40 #tick
      FadeOut: 5 #tick
      Enable: true
    Accept:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eAccept Downloading ResourcePack!"
      FadeIn: 5 #tick
      Stay: 40 #tick
      FadeOut: 5 #tick
      Enable: true
    Success:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eSuccess Downloading ResourcePack!"
      FadeIn: 5 #tick
      Stay: 40 #tick
      FadeOut: 5 #tick
      Enable: true
    Failed:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eFailed Downloading ResourcePack!"
      FadeIn: 5 #tick
      Stay: 40 #tick
      FadeOut: 5 #tick
      Enable: true
    Declined:
      Title: "&6&lEvelynResourcePack"
      SubTitle: "&eYou Declined ResourcePack!"
      FadeIn: 5 #tick
      Stay: 40 #tick
      FadeOut: 5 #tick
      Enable: true

  Messages:
    Bypass:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eBypass Downloading ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true
    Success:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eSuccess Downloading ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true
    Accept:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eAccept Downloading ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true
    Declined:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eYou Declined ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true
    Failed:
      Messages:
        - "&b&m                                                          &b"
        - ""
        - "              &6&lEvelynResourcePack"
        - "     &eFailed Downloading ResourcePack!"
        - ""
        - "&b&m                                                          &b"
      Enable: true

  Kick:
    Declined:
      Messages: "&6&lEvelynResourcePack\n&ePlease accept resourcepack!\n &eor enable resourcepack!"
      Enable: true
    Failed:
      Messages: "&6&lEvelynResourcePack\n&eFailed download resourcepack!"
      Enable: true