name: EvelynResourcePack
version: 1.6
main: com.josemarcellio.evelynresourcepack.Main
authors: [JoseMarcellio]
description: a lightweight resource pack downloader!
load: POSTWORLD
softdepend:
  - AuthMe
  - nLogin
  - OpeNLogin
commands:
  pack:
    aliases: [evelynpack, epack]
  resourcepack:
    aliases: [evelynresourcepack, eresourcepack]